substitutions:
  board: esp32dev

esphome:
  name: atlantic-v5-listener

esp32:
  board: ${board}
  framework:
    type: esp-idf

logger:

external_components:
  - source:
      type: local
      path: ../components

atlantic_v5:
  id: dhw
  mode: listener
  bus_capture: true
  hmi:
    uart_num: 1
    rx_pin: GPIO7
